const fs = require('fs');
const path = require('path');

const TOKENS_DIR = 'tokens';
const DIST = 'dist';
const AI = 'ai-context';

const themes = JSON.parse(fs.readFileSync('themes.json', 'utf8'));

function deepMerge(t, s) {
  for (const [k, v] of Object.entries(s)) {
    if (v && typeof v === 'object' && !('$value' in v)) {
      t[k] = t[k] && typeof t[k] === 'object' ? t[k] : {};
      deepMerge(t[k], v);
    } else t[k] = v;
  }
  return t;
}

function loadTheme(name) {
  return themes[name].reduce(
    (acc, set) => deepMerge(acc, JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, set + '.json'), 'utf8'))),
    {}
  );
}

function getByPath(o, p) { return p.split('.').reduce((a, k) => (a == null ? a : a[k]), o); }

function resolve(v, root, stack = []) {
  if (typeof v === 'string') {
    return v.replace(/\{([^}]+)\}/g, (_, p) => {
      if (stack.includes(p)) throw new Error('Circular ref: ' + p);
      const t = getByPath(root, p);
      if (!t || !('$value' in t)) throw new Error('Bad ref: {' + p + '}');
      return resolve(t.$value, root, [...stack, p]);
    });
  }
  if (Array.isArray(v)) return v.map((x) => resolve(x, root, stack));
  if (v && typeof v === 'object') {
    return Object.fromEntries(Object.entries(v).map(([k, x]) => [k, resolve(x, root, stack)]));
  }
  return v;
}

function flatten(o, prefix = '', out = []) {
  for (const [k, v] of Object.entries(o)) {
    const p = prefix ? `${prefix}.${k}` : k;
    if (v && typeof v === 'object' && !('$value' in v)) flatten(v, p, out);
    else out.push({ path: p, token: v });
  }
  return out;
}

const PX = new Set(['spacing', 'fontSizes', 'lineHeights', 'borderRadius', 'dimension', 'sizing', 'paragraphSpacing']);
const WEIGHTS = { Regular: 400, Medium: 500, SemiBold: 600, Bold: 700 };

function cssValue(token) {
  const v = token.$value;
  if (PX.has(token.$type) && typeof v === 'number') return `${v}px`;
  if (token.$type === 'fontWeights') return String(WEIGHTS[v] ?? v);
  return String(v);
}

function varName(p) {
  return '--' + p.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase().split('.').join('-');
}

const light = loadTheme('light');
const dark = loadTheme('dark');
const lightLeaves = flatten(light).map((l) => ({ ...l, resolved: resolve(l.token.$value, light) }));
const darkLeaves = flatten(dark).map((l) => ({ ...l, resolved: resolve(l.token.$value, dark) }));
const darkMap = new Map(darkLeaves.map((d) => [d.path, d]));

fs.mkdirSync(DIST, { recursive: true });
fs.mkdirSync(AI, { recursive: true });

// ---------- dist/tokens.css ----------
const css = ['/* Generated by scripts/build.js — do not edit by hand */', ':root {'];
for (const l of lightLeaves) {
  if (l.token.$type === 'typography') continue;
  css.push(`  ${varName(l.path)}: ${cssValue({ ...l.token, $value: l.resolved })};`);
}
css.push('}', '', '[data-theme="dark"] {');
let darkCount = 0;
for (const l of lightLeaves) {
  if (l.token.$type === 'typography') continue;
  const d = darkMap.get(l.path);
  if (d && String(d.resolved) !== String(l.resolved)) {
    css.push(`  ${varName(l.path)}: ${cssValue({ ...d.token, $value: d.resolved })};`);
    darkCount++;
  }
}
css.push('}', '', '/* Typography utility classes (theme-independent) */');

const typeSet = JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, 'semantic.type.json'), 'utf8'));
for (const [group, tokens] of Object.entries(typeSet)) {
  for (const [name, token] of Object.entries(tokens)) {
    const r = resolve(token.$value, light);
    const props = [
      `font-family: "${r.fontFamily}";`,
      `font-size: ${r.fontSize}px;`,
      `line-height: ${r.lineHeight}px;`,
      `font-weight: ${WEIGHTS[r.fontWeight] ?? r.fontWeight};`,
    ];
    if (r.letterSpacing) props.push(`letter-spacing: ${r.letterSpacing};`);
    if (r.paragraphSpacing) props.push(`margin-bottom: ${r.paragraphSpacing}px;`);
    css.push(`.type-${group}-${name} {`);
    props.forEach((p) => css.push(`  ${p}`));
    css.push('}');
  }
}
fs.writeFileSync(path.join(DIST, 'tokens.css'), css.join('\n') + '\n');

// ---------- dist/tokens.ts ----------
function nest(leaves) {
  const root = {};
  for (const l of leaves) {
    const parts = l.path.split('.');
    let cur = root;
    parts.slice(0, -1).forEach((k) => (cur = cur[k] = cur[k] || {}));
    cur[parts.at(-1)] = l.resolved;
  }
  return root;
}
fs.writeFileSync(
  path.join(DIST, 'tokens.ts'),
  `/* Generated by scripts/build.js — do not edit by hand */\nexport const tokens = ${JSON.stringify(nest(lightLeaves), null, 2)} as const;\nexport type Tokens = typeof tokens;\n`
);

// ---------- ai-context/tokens-reference.md ----------
const md = [];
md.push('# 2GIS Design System — справочник токенов для ИИ-агентов', '');
md.push('Правила: интерфейсы собираются ТОЛЬКО из semantic-токенов и классов .type-*.');
md.push('primitive.* — справочная информация о шкалах, напрямую в коде не используется.');
md.push('Темы: пути токенов идентичны, значения переключаются через [data-theme="dark"].', '');
md.push('## Семантические цвета (light / dark)', '');
md.push('| Токен | Light | Dark | Применение |');
md.push('|---|---|---|---|');
for (const l of lightLeaves.filter((x) => /^(text-and-icon|surfaces|stroke)/.test(x.path))) {
  const d = darkMap.get(l.path);
  md.push(`| ${l.path} | ${l.resolved} | ${d ? d.resolved : '—'} | ${l.token.$description || ''} |`);
}
md.push('', '## Отступы и радиусы', '');
md.push('| Токен | Значение | Применение |');
md.push('|---|---|---|');
for (const l of lightLeaves.filter((x) => ['spacing', 'borderRadius'].includes(x.token.$type))) {
  md.push(`| ${l.path} | ${cssValue({ ...l.token, $value: l.resolved })} | ${l.token.$description || ''} |`);
}
md.push('', '## Типографика (классы в tokens.css)', '');
md.push('| Класс | Состав | Применение |');
md.push('|---|---|---|');
for (const [group, tokens] of Object.entries(typeSet)) {
  for (const [name, token] of Object.entries(tokens)) {
    const r = resolve(token.$value, light);
    md.push(`| .type-${group}-${name} | ${r.fontFamily}, ${r.fontSize}/${r.lineHeight}, ${WEIGHTS[r.fontWeight] ?? r.fontWeight}, tracking ${r.letterSpacing || '0'} | ${token.$description || ''} |`);
  }
}
md.push('', '## Палитра (справочно, не использовать напрямую)', '');
md.push('| Токен | Hex | Примечание |');
md.push('|---|---|---|');
for (const l of flatten(JSON.parse(fs.readFileSync(path.join(TOKENS_DIR, 'primitive.color.json'), 'utf8')))) {
  md.push(`| ${l.path} | ${l.token.$value} | ${l.token.$description || ''} |`);
}
fs.writeFileSync(path.join(AI, 'tokens-reference.md'), md.join('\n') + '\n');

console.log(`OK  tokens.css: ${lightLeaves.filter((l) => l.token.$type !== 'typography').length} var light, ${darkCount} var dark, 24 type-класса`);
console.log('OK  tokens.ts: nested object light');
console.log('OK  ai-context/tokens-reference.md: справочник для ИИ');